# Generated by Django 5.2.1 on 2026-04-04 15:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='senha_hash', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('profissao', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('faltas_consecutivas', models.SmallIntegerField(default=0)),
                ('bloqueado_online', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'codigo_verificacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracao_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funcionalidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('validade_meses', models.SmallIntegerField(default=12)),
            ],
            options={
                'db_table': 'pacote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao_minutos', models.SmallIntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'procedimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profissional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('valor_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao_preco', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Faltou')], default='AGENDADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reagendado_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagendamentos', to='aranha_estetica.atendimento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.cliente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.procedimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.profissional')),
            ],
            options={
                'db_table': 'atendimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnotacaoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='aranha_estetica.atendimento')),
            ],
            options={
                'db_table': 'anotacao_sessao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField()),
                ('tabela_afetada', models.CharField(blank=True, max_length=100, null=True)),
                ('id_registro_afetado', models.IntegerField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LEMBRETE', 'Lembrete'), ('CONFIRMACAO', 'Confirmação'), ('CANCELAMENTO', 'Cancelamento'), ('NPS', 'Pesquisa NPS')], default='LEMBRETE', max_length=30)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'E-mail')], default='WHATSAPP', max_length=20)),
                ('status_envio', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20)),
                ('resposta_cliente', models.CharField(blank=True, choices=[('CONFIRMOU', 'Confirmou'), ('CANCELOU', 'Cancelou')], max_length=20, null=True)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.atendimento')),
            ],
            options={
                'db_table': 'notificacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PacoteCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='ATIVO', max_length=20)),
                ('data_expiracao', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_comprados', to='aranha_estetica.cliente')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.pacote')),
            ],
            options={
                'db_table': 'pacote_cliente',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.perfil'),
        ),
        migrations.CreateModel(
            name='PerfilFuncionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.funcionalidade')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.perfil')),
            ],
            options={
                'db_table': 'perfil_funcionalidade',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='funcionalidades',
            field=models.ManyToManyField(through='aranha_estetica.PerfilFuncionalidade', to='aranha_estetica.funcionalidade'),
        ),
        migrations.CreateModel(
            name='ItemPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sessoes', models.SmallIntegerField(default=1)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='aranha_estetica.pacote')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.procedimento')),
            ],
            options={
                'db_table': 'item_pacote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('vigente_desde', models.DateField(default=datetime.date.today)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.procedimento')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.profissional')),
            ],
            options={
                'db_table': 'preco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desejada', models.DateField()),
                ('turno_desejado', models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=20, null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('token_reserva', models.CharField(blank=True, max_length=64, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.cliente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.procedimento')),
                ('profissional_desejado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.profissional')),
            ],
            options={
                'db_table': 'lista_espera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.SmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.profissional')),
            ],
            options={
                'db_table': 'disponibilidade_profissional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.profissional')),
            ],
            options={
                'db_table': 'bloqueio_agenda',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='profissional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.profissional'),
        ),
        migrations.CreateModel(
            name='ProfissionalProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.procedimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.profissional')),
            ],
            options={
                'db_table': 'profissional_procedimento',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='procedimento',
            name='profissionais',
            field=models.ManyToManyField(through='aranha_estetica.ProfissionalProcedimento', to='aranha_estetica.profissional'),
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
                ('imagem_url', models.TextField(blank=True, null=True)),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.procedimento')),
            ],
            options={
                'db_table': 'promocao',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.promocao'),
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('contraindicacoes', models.TextField(blank=True, null=True)),
                ('historico_saude', models.TextField(blank=True, null=True)),
                ('medicamentos_uso', models.TextField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.cliente')),
            ],
            options={
                'db_table': 'prontuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProntuarioPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo_resposta', models.CharField(choices=[('TEXTO', 'Texto livre'), ('BOOLEAN', 'Sim / Não'), ('SELECAO', 'Seleção')], max_length=50)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prontuario_pergunta',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo_resposta__in', ['TEXTO', 'BOOLEAN', 'SELECAO'])), name='chk_prontuario_pergunta_tipo')],
            },
        ),
        migrations.CreateModel(
            name='ProntuarioResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True)),
                ('resposta_boolean', models.BooleanField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.prontuariopergunta')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.prontuario')),
            ],
            options={
                'db_table': 'prontuario_resposta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SessaoPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='sessao_pacote_vinculada', to='aranha_estetica.atendimento')),
                ('pacote_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_realizadas', to='aranha_estetica.pacotecliente')),
            ],
            options={
                'db_table': 'sessao_pacote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VersaoTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LGPD', 'LGPD / Privacidade'), ('PROCEDIMENTO', 'Termo de Procedimento')], max_length=20)),
                ('titulo', models.TextField()),
                ('conteudo', models.TextField()),
                ('versao', models.CharField(max_length=20)),
                ('vigente_desde', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.procedimento')),
            ],
            options={
                'db_table': 'versao_termo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssinaturaTermoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.atendimento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.cliente')),
                ('versao_termo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.versaotermo')),
            ],
            options={
                'db_table': 'assinatura_termo_procedimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AceitePrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.cliente')),
                ('versao_termo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.versaotermo')),
            ],
            options={
                'db_table': 'aceite_privacidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.SmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('alerta_enviado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.atendimento')),
            ],
            options={
                'db_table': 'avaliacao_nps',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('nota__gte', 0), ('nota__lte', 10)), name='chk_avaliacao_nps_nota')],
            },
        ),
        migrations.AddConstraint(
            model_name='pacotecliente',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ATIVO', 'FINALIZADO', 'CANCELADO', 'EXPIRADO'])), name='chk_pacote_cliente_status'),
        ),
        migrations.AlterUniqueTogether(
            name='perfilfuncionalidade',
            unique_together={('perfil', 'funcionalidade')},
        ),
        migrations.AlterUniqueTogether(
            name='itempacote',
            unique_together={('pacote', 'procedimento')},
        ),
        migrations.AddConstraint(
            model_name='listaespera',
            constraint=models.CheckConstraint(condition=models.Q(('turno_desejado__isnull', True), ('turno_desejado__in', ['MANHA', 'TARDE', 'NOITE']), _connector='OR'), name='chk_lista_espera_turno'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadeprofissional',
            constraint=models.CheckConstraint(condition=models.Q(('dia_semana__gte', 1), ('dia_semana__lte', 7)), name='chk_disponibilidade_dia_semana'),
        ),
        migrations.AlterUniqueTogether(
            name='profissionalprocedimento',
            unique_together={('profissional', 'procedimento')},
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AGENDADO', 'CONFIRMADO', 'REALIZADO', 'CANCELADO', 'FALTOU'])), name='chk_atendimento_status'),
        ),
        migrations.AlterUniqueTogether(
            name='prontuarioresposta',
            unique_together={('prontuario', 'pergunta')},
        ),
        migrations.AddConstraint(
            model_name='versaotermo',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['LGPD', 'PROCEDIMENTO'])), name='chk_versao_termo_tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='assinaturatermoprocedimento',
            unique_together={('cliente', 'versao_termo')},
        ),
        migrations.AlterUniqueTogether(
            name='aceiteprivacidade',
            unique_together={('cliente', 'versao_termo')},
        ),
    ]
