# Generated by Django 5.2.1 on 2026-04-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0002_atendimento_idx_atendimento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='token_cancelamento',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
