# Generated by Django 5.2.1 on 2026-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0003_add_token_cancelamento_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='categoria',
            field=models.CharField(choices=[('FACIAL', 'Facial'), ('CORPORAL', 'Corporal'), ('CAPILAR', 'Capilar'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
    ]
