# Generated by Django 5.2.1 on 2026-04-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0018_excecaodisponibilidade_procedimento_buffer_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='ics_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
