# Generated by Django 5.2.1 on 2026-04-29 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0019_profissional_ics_token_profissional_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('trigger', models.CharField(choices=[('ON_BOOK', 'Ao agendar'), ('BEFORE_EVENT', 'Antes do evento'), ('AFTER_EVENT', 'Apos o evento'), ('ON_CANCEL', 'Ao cancelar'), ('ON_NO_SHOW', 'No-show registrado')], max_length=20)),
                ('offset_minutos', models.IntegerField(default=0)),
                ('acao', models.CharField(choices=[('SEND_EMAIL', 'Enviar e-mail'), ('SEND_SMS', 'Enviar SMS'), ('SEND_WHATSAPP', 'Enviar WhatsApp'), ('SEND_PUSH', 'Web push'), ('WEBHOOK', 'Webhook HTTP')], max_length=20)),
                ('template', models.TextField(blank=True, default='')),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'workflow_regra',
                'managed': True,
                'indexes': [models.Index(fields=['ativo', 'trigger'], name='idx_workflow_ativo_trigger')],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True)),
                ('p256dh', models.CharField(max_length=140)),
                ('auth', models.CharField(max_length=80)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_falha_em', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_push_subscription',
                'managed': True,
                'indexes': [models.Index(fields=['user', 'ativo'], name='idx_pushsub_user_ativo')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Sucesso'), ('FALHOU', 'Falhou'), ('SKIPPED', 'Pulado (duplicado)')], max_length=10)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.atendimento')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.workflowregra')),
            ],
            options={
                'db_table': 'workflow_execucao',
                'managed': True,
                'indexes': [models.Index(fields=['regra', 'atendimento'], name='idx_wexec_regra_atend'), models.Index(fields=['-executado_em'], name='idx_wexec_executado')],
                'constraints': [models.UniqueConstraint(fields=('regra', 'atendimento'), name='uniq_wexec_regra_atend')],
            },
        ),
    ]
