# Generated by Django 5.2.1 on 2026-04-29 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0020_workflowregra_webpushsubscription_workflowexecucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueioagenda',
            name='recorrencia_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloqueioagenda',
            name='regra_recorrencia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profissional',
            name='gcal_calendar_id',
            field=models.CharField(blank=True, default='primary', max_length=200),
        ),
        migrations.AddField(
            model_name='profissional',
            name='gcal_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profissional',
            name='gcal_sync_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profissional',
            name='gcal_ultimo_sync_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FormularioAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('escopo', models.CharField(choices=[('GLOBAL', 'Global (todo agendamento)'), ('CATEGORIA', 'Por categoria de procedimento'), ('PROCEDIMENTO', 'Por procedimento especifico')], default='GLOBAL', max_length=20)),
                ('categoria', models.CharField(blank=True, default='', max_length=20)),
                ('schema_json', models.JSONField(default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.procedimento')),
            ],
            options={
                'db_table': 'formulario_anamnese',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RespostaAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas_json', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.atendimento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.cliente')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.formularioanamnese')),
            ],
            options={
                'db_table': 'resposta_anamnese',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='formularioanamnese',
            index=models.Index(fields=['ativo', 'escopo'], name='idx_anamnese_ativo_escopo'),
        ),
        migrations.AddIndex(
            model_name='respostaanamnese',
            index=models.Index(fields=['cliente', '-criado_em'], name='idx_anamnese_resp_cli'),
        ),
        migrations.AddIndex(
            model_name='respostaanamnese',
            index=models.Index(fields=['atendimento'], name='idx_anamnese_resp_atend'),
        ),
    ]
