# Generated by Django 5.2.1 on 2026-05-04 03:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0021_bloqueioagenda_recorrencia_ate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('cor', models.CharField(default='#C9A84C', help_text='Hex color', max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_url',
            field=models.URLField(blank=True, default='', help_text='URL S3 / storage', max_length=600),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indicado_por',
            field=models.ForeignKey(blank=True, help_text='Cliente que indicou este (programa fidelidade)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes', to='aranha_estetica.cliente'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Biografia publica do profissional'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
        migrations.CreateModel(
            name='CreditoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='aranha_estetica.cliente')),
            ],
            options={
                'db_table': 'credito_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Ex: "Plano facial Maria 2026"', max_length=150)),
                ('objetivo', models.TextField(blank=True, default='', help_text='Resultado esperado')),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluido'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='aranha_estetica.cliente')),
                ('profissional_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.profissional')),
            ],
            options={
                'db_table': 'plano_tratamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessoes_previstas', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sessoes_realizadas', models.SmallIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aranha_estetica.procedimento')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='aranha_estetica.planotratamento')),
            ],
            options={
                'db_table': 'item_plano_tratamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('descricao', models.TextField(blank=True, default='')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('ML', 'Mililitro'), ('G', 'Grama'), ('SESSAO', 'Sessao')], default='UN', max_length=10)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Alerta quando estoque atual <= minimo', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fornecedor', models.CharField(blank=True, default='', max_length=200)),
                ('validade_proxima', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': True,
                'indexes': [models.Index(fields=['ativo', 'nome'], name='idx_produto_ativo_nome')],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (compra)'), ('SAIDA', 'Saida (consumo atendimento)'), ('AJUSTE', 'Ajuste manual'), ('PERDA', 'Perda/vencimento')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_consumidos', to='aranha_estetica.atendimento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimentos', to='aranha_estetica.produto')),
            ],
            options={
                'db_table': 'movimento_estoque',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClienteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicada_em', models.DateTimeField(auto_now_add=True)),
                ('aplicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_tags', to='aranha_estetica.cliente')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aranha_estetica.tag')),
            ],
            options={
                'db_table': 'cliente_tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FotoAntesDepois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ANTES', 'Antes'), ('DURANTE', 'Durante'), ('DEPOIS', 'Depois')], max_length=10)),
                ('url', models.URLField(help_text='URL S3 / Cloudinary / storage externo', max_length=600)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=600)),
                ('descricao', models.TextField(blank=True, default='')),
                ('capturada_em', models.DateTimeField()),
                ('consent_uso_imagem', models.BooleanField(default=False, help_text='Cliente autorizou uso (marketing/portfolio). LGPD obrigatorio.')),
                ('consent_uso_imagem_em', models.DateTimeField(blank=True, null=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_clinicas', to='aranha_estetica.atendimento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='aranha_estetica.cliente')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.procedimento')),
            ],
            options={
                'db_table': 'foto_antes_depois',
                'managed': True,
                'indexes': [models.Index(fields=['cliente', '-capturada_em'], name='idx_foto_cli_data'), models.Index(fields=['atendimento'], name='idx_foto_atend'), models.Index(fields=['tipo'], name='idx_foto_tipo')],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Credito (vale, refund, ajuste+)'), ('DEBITO', 'Debito (uso, ajuste-)')], max_length=10)),
                ('origem', models.CharField(choices=[('VALE_PRESENTE', 'Vale presente'), ('CANCELAMENTO', 'Refund cancelamento'), ('AJUSTE_MANUAL', 'Ajuste manual'), ('USO_AGENDAMENTO', 'Uso em agendamento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_apos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.atendimento')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='aranha_estetica.creditocliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimento_credito',
                'managed': True,
                'indexes': [models.Index(fields=['credito', '-criado_em'], name='idx_movcred_cred')],
            },
        ),
        migrations.CreateModel(
            name='PatchTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('substancia', models.CharField(help_text='Ex: acido hialuronico XYZ, anestesico topico', max_length=200)),
                ('aplicado_em', models.DateTimeField()),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('PENDENTE', 'Pendente avaliacao'), ('NEGATIVO', 'Negativo (sem reacao)'), ('POSITIVO', 'Positivo (reacao)'), ('INCONCLUSIVO', 'Inconclusivo')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_tests', to='aranha_estetica.cliente')),
                ('procedimento', models.ForeignKey(blank=True, help_text='Procedimento que motivou o teste', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.procedimento')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.profissional')),
            ],
            options={
                'db_table': 'patch_test',
                'managed': True,
                'indexes': [models.Index(fields=['cliente', '-aplicado_em'], name='idx_patch_cli_data'), models.Index(fields=['resultado'], name='idx_patch_resultado')],
            },
        ),
        migrations.AddIndex(
            model_name='planotratamento',
            index=models.Index(fields=['cliente', '-criado_em'], name='idx_plano_cli'),
        ),
        migrations.AddIndex(
            model_name='planotratamento',
            index=models.Index(fields=['status'], name='idx_plano_status'),
        ),
        migrations.AddIndex(
            model_name='itemplanotratamento',
            index=models.Index(fields=['plano'], name='idx_itemplano_plano'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['produto', '-criado_em'], name='idx_movest_prod_data'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['atendimento'], name='idx_movest_atend'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['tipo'], name='idx_movest_tipo'),
        ),
        migrations.AddIndex(
            model_name='clientetag',
            index=models.Index(fields=['tag'], name='idx_cliente_tag_tag'),
        ),
        migrations.AddConstraint(
            model_name='clientetag',
            constraint=models.UniqueConstraint(fields=('cliente', 'tag'), name='uniq_cliente_tag'),
        ),
    ]
