# Generated by Django 5.2.1 on 2026-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0039_valor_pago_nota_validators_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaonps',
            name='aprovado_publicacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacaonps',
            name='autoriza_publicacao',
            field=models.BooleanField(default=False),
        ),
    ]
