# Generated by Django 5.2.1 on 2026-03-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='data_hora_resposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='resposta_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(default='LEMBRETE', max_length=30),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='canal',
            field=models.CharField(default='WHATSAPP', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status_envio',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
    ]
