# Generated by Django 5.2.1 on 2026-03-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'codigo_verificacao',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='atendimento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bloqueioagenda',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disponibilidadeprofissional',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='funcionalidade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='perfilfuncionalidade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='preco',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='procedimento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='profissionalprocedimento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prontuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prontuariopergunta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prontuarioresposta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='termoconsentimento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id_promocao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
                ('imagem_url', models.CharField(blank=True, max_length=500, null=True)),
                ('procedimento', models.ForeignKey(blank=True, db_column='id_procedimento', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.procedimento')),
            ],
            options={
                'db_table': 'promocao',
                'managed': True,
            },
        ),
    ]
