# Generated by Django 5.2.1 on 2026-04-29 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0017_consent_whatsapp_confirmacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcecaoDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('FOLGA', 'Folga'), ('HORARIO_DIFERENTE', 'Horario Diferente')], max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'excecao_disponibilidade',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='procedimento',
            name='buffer_minutos',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profissional',
            name='max_advance_dias',
            field=models.SmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='profissional',
            name='min_notice_horas',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.CheckConstraint(condition=models.Q(('buffer_minutos__gte', 0), ('buffer_minutos__lte', 120)), name='chk_procedimento_buffer_range'),
        ),
        migrations.AddConstraint(
            model_name='profissional',
            constraint=models.CheckConstraint(condition=models.Q(('min_notice_horas__gte', 0), ('min_notice_horas__lte', 720)), name='chk_profissional_min_notice_range'),
        ),
        migrations.AddConstraint(
            model_name='profissional',
            constraint=models.CheckConstraint(condition=models.Q(('max_advance_dias__gte', 1), ('max_advance_dias__lte', 365)), name='chk_profissional_max_advance_range'),
        ),
        migrations.AddField(
            model_name='excecaodisponibilidade',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional'),
        ),
        migrations.AddIndex(
            model_name='excecaodisponibilidade',
            index=models.Index(fields=['profissional', 'data'], name='idx_excecao_prof_data'),
        ),
        migrations.AddConstraint(
            model_name='excecaodisponibilidade',
            constraint=models.UniqueConstraint(fields=('profissional', 'data', 'tipo'), name='uniq_excecao_prof_data_tipo'),
        ),
        migrations.AddConstraint(
            model_name='excecaodisponibilidade',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'FOLGA'), models.Q(('tipo', 'HORARIO_DIFERENTE'), ('hora_inicio__isnull', False), ('hora_fim__isnull', False)), _connector='OR'), name='chk_excecao_horario_completo'),
        ),
    ]
